### ISSUE TITLE
UTM policy/State of the art section should include a review of efforts in the EU

### ISSUE THREAD

**Issue by sayandeep-ai** [iSPIRT/pushpaka#3]
1. [Swiss Conops](https://github.com/iSPIRT/pushpaka/blob/eeb2055dd5a87e5444f02edb051007d4dd2a3039/docs/work-items/i05.md?plain=1#L32)
2. [U-Space](https://github.com/iSPIRT/pushpaka/blob/eeb2055dd5a87e5444f02edb051007d4dd2a3039/docs/work-items/i05.md?plain=1#L36)
3. [GUTMA](https://github.com/iSPIRT/pushpaka/blob/eeb2055dd5a87e5444f02edb051007d4dd2a3039/docs/work-items/i05.md?plain=1#L27)
4. Any other relevant effort

**Comment by hrishiballal** [comment]
I have now pushed the first version for review.

**Comment by sayandeep-ai** [comment]
Cheers. Just FYI for next time onward, the UTM Policy doc (I05) has its own branch `i05-dev`, `master` is for common, `minutes` for MOMs. I usually merge everything into `dev` branch which gets deployed to the site.

Please note above @sraviku2 @manishshuklaGMC @mnihalm @flyamigo @
